### PR TITLE
Added Outline View

### PR DESCRIPTION
**Pull request by rishabh-ti**
Outline View displays a list of components with proper indentation to show child parent relationship. Would be helpful in case we add Overlay components like Modal, Alert, etc
Screenshot 2022-11-22 at 7 51 57 PM

### CODE REVIEW

**Comment by vinayak-sachdeva** [comment]
When would someone prefer this as opposed to the builder mode?

**Comment by rishabh-ti** [comment]
> When would someone prefer this as opposed to the builder mode?

It is not that helpful right now. But if add overlay components in the future like modal, dialog, popover, etc. We won't be able to see those components in the Builder Mode. 

We can click on the component name from the Outline View and will highlight and bring up that component for editing. This feature is not implemented right now.

**Comment by vickybiswas** [comment]
Should this not be a part of the right sidebar?

**Comment by vickybiswas** [comment]
@rishabh-ti

**Comment by rishabh-ti** [comment]
> Should this not be a part of the right sidebar?

Yes that would make more sense. This is on low priority at the moment.

**Pull request closed without merging**
