### PR TITLE
Feature/alert

### PR DESCRIPTION
**Pull request by ayodeji-ti**

### CODE REVIEW

**Review by rishabh-ti — COMMENTED** [review]
Why is this PR required? Don't we already have an Alert component?

**Comment by ayodeji-ti** [comment]
To be honest, I don't really think this PR is required, we don't have an alert component, but an alert component is basically a modal with less capabilities, i.e the modal body can be composed of any react element, but the alert body is typically just for text, so anything that can be done with an alert can basically be done with a modal.

**Comment by rishabh-ti** [comment]
> To be honest, I don't really think this PR is required, we don't have an alert component, but an alert component is basically a modal with less capabilities, i.e the modal body can be composed of any react element, but the alert body is typically just for text, so anything that can be done with an alert can basically be done with a modal.

Agreed. But there is already an Alert component in openchakra with an alert title, desctiption, icon, etc. Anyways, this is not needed then. We can prolly close this then.

**Comment by ayodeji-ti** [comment]
closing now

**Pull request closed without merging**
