### PR TITLE
deleting parameter no longer causes a bug

### PR DESCRIPTION
**Pull request by ayodeji-ti**

### CODE REVIEW

**Review by rishabh-ti — COMMENTED** [review]
Does this issue still exist in master branch? Is this PR required? 
Have you tested this out thoroughly with parameters and props?

**Comment by ayodeji-ti** [comment]
Issue still exists, I have tested it out in different cases, everything seems fine, I just want you to take a close look at the change I made here, we can have a meet about this at your earliest convenience

**Comment by rishabh-ti** [comment]
> Issue still exists, I have tested it out in different cases, everything seems fine, I just want you to take a close look at the change I made here, we can have a meet about this at your earliest convenience

This change is already included in #61.

**Comment by ayodeji-ti** [comment]
yes I added that there because everytime I deleted the component with refs and the parameter got deleted, the same error was popping up, that's why I would like this PR to be resolved before merging that one

**Comment by rishabh-ti** [comment]
Merged #66 and therefore closing this

**Pull request closed without merging**
