### PR TITLE
Fix/delete refs

### PR DESCRIPTION
**Pull request by ayodeji-ti**
Deleting an input or the parent of one or more inputs at any level will delete all related paramters

### CODE REVIEW

**Review by rishabh-ti — COMMENTED** [review]
Does this issue still exist in master branch? Is this PR required?
Have you tested this out thoroughly with all kinds of components with refs and their addition/deletion?

**Comment by ayodeji-ti** [comment]
Yes the issue still exists, I've tested it out with input, inputGroups, formControlLabel, I tested when a parent of the component is deleted etc etc, I can say I thoroughly tested this out

**Comment by ayodeji-ti** [comment]
Adding components doesn't get affected at all, this only affects deleting

**Review by rishabh-ti — APPROVED** [review]
I assume the refs are deleted in the code generated as well.

**Pull request merged**
