### PR TITLE
Slider Component - Initial Commit

### PR DESCRIPTION
**Pull request by Ishaan-ti**

### CODE REVIEW

**Review by ayodeji-ti — COMMENTED** [review]
in the componentsList.ts you didn't add the slider components to the componentsList array.

It's not compulsory but it's good to add those for built in components

**Comment by vickybiswas** [comment]
@Ishaan-ti are the comments addressed?

**Comment by vickybiswas** [comment]
> in the componentsList.ts you didn't add the slider components to the componentsList array.
> 
> It's not compulsory but it's good to add those for built in components

Ayodeji please be more specific why it is good

**Comment by Ishaan-ti** [comment]
Added slider components to componentList array

**Pull request closed without merging**
